config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/index'
  post 'home/cart', to: 'home#cart', as: 'cart'
  post 'home/clear_cart', to: 'home#clear_cart', as: 'clear_cart'
  post '/order', to: 'home#order'

  get 'bookings/index', to: 'bookings#index'
  get 'bookings/show/:amount', to: 'bookings#show', as: 'bookings_show'
  get 'bookings/checkout', to: 'bookings#checkout', as: 'checkout'
  get 'bookings/failure', to: 'bookings#failure'
  post 'bookings/save', to: 'bookings#save_payment_method', as: 'save_payment_method'

  get 'payment_methods/index', to: 'payment_methods_#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    # passing a nil payment_method_token because I won't need it and I don't want
    # to spend time creating a different service class for this API call
    render json: Cashier.new(nil).list_transactions[:subject]
  end

  def show
    @amount = params[:amount]
    session[:flights] = []
  end

  def checkout
    @flights = session[:flights]
  end

  def failure
    @message = flash[:alert]
  end

  def save_payment_method
    response = Cashier.new(session[:pm_token]).retain
    response_body = response[:subject]['transaction']
    puts response[:subject]

    if response.errors?
      puts response.errors
      render :file => "#{Rails.root}/public/500.html", status: 500
    elsif response_body['succeeded']
      @digits = response_body['payment_method']['last_four_digits']
      @name = response_body['payment_method']['first_name'] + ' ' + response_body['payment_method']['last_name']
    else
      @message = response_body['message']
    end

    session[:pm_token] = nil
    render 'save'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'net/http'
  require 'uri'

  CITIES = %w(Portland Seattle Denver Raliegh-Durham Chicago Dallas Tampa)

  def index
    @flights = generate_flights
  end

  def cart
    session[:flights] ||= []
    session[:flights] << params[:flight]
  end

  def clear_cart
    session[:flights] = []
  end

  def order
    pm_token = params[:payment_method_token]
    amount = (params[:amount].to_f * 100).to_i
    response = Cashier.new(pm_token, { amount: amount, receiver: params['receiver'] }).call
    response_body = response[:subject]['transaction']
    puts response[:subject]

    if response.errors?
      puts response.errors
      render :file => "#{Rails.root}/public/500.html",  status: 500
    elsif response_body['succeeded']
      session[:pm_token] = response_body['payment_method']['token']
      redirect_to bookings_show_path(params[:amount])
    else
      flash[:alert] = response_body['message']
      redirect_to bookings_failure_path
    end
  end

  private

  def generate_flights
    arr = []
    6.times do
      departure = CITIES.sample
      arr << {
        departure: departure,
        destination: (CITIES - [departure]).sample,
        cost: rand(100..2000.1).truncate(2)
      }
    end
    arr
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  def index
    # passing a nil payment_method_token because I won't need it and I don't want
    # to spend time creating a different service class for this API call
    render json: Cashier.new(nil).list_payment_methods[:subject]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_to_cart(flight)
    cookies[:flights] ||= []
    cookies[:flights] << flight
  end
end

app/views/bookings/checkout.html.erb
<%
  total_cost = sprintf("%.2f", @flights.map {|f| f['cost'].to_f}.sum.truncate(2)) if @flights.present?
%>

<head>
  <script src="https://core.spreedly.com/iframe/iframe-v1.min.js"></script>
</head>

<% if @flights.present? %>
  <h2>You have chosen the following flights</h2>
  <% @flights.each do |flight| %>
    <p>From <%= flight['departure'] %> to <%= flight['destination'] %> at a cost of $<%=flight['cost'] %></p>
  <% end %>
  <h2>Your total cost is <%= total_cost %></h2>
  <form class="iframe" id="payment-form" controller="home" action="/order" method="post" onsubmit='submitPaymentForm(); return false;'>

    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
    <input type="hidden" name="payment_method_token" id="payment_method_token">
    <input type="hidden" name="amount" value="<%= total_cost %>">
    <input type="hidden" name="receiver" value="none">

    <label for="full_name">Name</label>
    <input type="text" id="full_name" name="full_name"><br/>

    <label>Credit Card Number</label>
    <div id="spreedly-number" style="width:225px; height:28px;"></div><br/>

    <label for="month">Month</label>
    <input type="text" id="month" name="month" maxlength="2">
    <label for="month">Year</label>
    <input type="text" id="year" name="year" maxlength="4"><br/>

    <label>CVV</label>
    <div id="spreedly-cvv" style="width:60px; height:28px;"></div><br/>

    <input class="btn" id="submit-button" type="submit" value="Pay Now" disabled>

  </form>
  <%= link_to "Return Home", home_index_path, :"data-turbolinks"=>false %>
<% else %>
  <p>Your cart is empty. Return to the <%= link_to "flights", home_index_path, :"data-turbolinks"=>false %> page to book a flight!</p>
<% end %>

<script>
    Spreedly.init("3C7NRMKIvw2hUvkgic6P5AP0UsH", {
      "numberEl": "spreedly-number",
      "cvvEl": "spreedly-cvv"
    });
        
    Spreedly.on("ready", function () {
      var submitButton = document.getElementById('submit-button');
      submitButton.disabled = false;

      Spreedly.setFieldType("number", "text")
      Spreedly.setNumberFormat("prettyFormat")
      Spreedly.setPlaceholder("number", "4111 1111 1111 1111")
      Spreedly.setPlaceholder("cvv", "123")

      Spreedly.setStyle('number','height: 13px; width: 67%; border-radius: 3px; border: 1px solid #ccc; background: snow; padding: .65em .5em; font-size: 91%;');
      Spreedly.setStyle('cvv', 'height: 13px; border-radius: 3px; border: 1px solid #ccc; background: snow; padding: .65em .5em; font-size: 91%;');
    });


    function submitPaymentForm() {
      var requiredFields = {};

      requiredFields["full_name"] = document.getElementById("full_name").value;
      requiredFields["month"] = document.getElementById("month").value;
      requiredFields["year"] = document.getElementById("year").value;

      Spreedly.tokenizeCreditCard(requiredFields);
    }

    Spreedly.on('paymentMethod', function(token, pmData) {
      // Set the token in the hidden form field
      var tokenField = document.getElementById("payment_method_token");
      tokenField.setAttribute("value", token);

      // Submit the form
      var masterForm = document.getElementById('payment-form');
      masterForm.submit();
    });
</script>

app/views/bookings/failure.html.erb
<h2>Your purchase failed with a message: <%= @message %></h2>
<%= link_to "Return Home", home_index_path, :"data-turbolinks"=>false %>

app/views/bookings/save.html.erb
<% if @message.nil? %>
  <h2>You have sucessfully saved the following card for future use:</h2>
  <ul>
    <li><strong>Name:</strong> <%= @name %></li>
    <li><strong>Last 4 digits:</strong> <%= @digits %></li>
  </ul>
<% else %>
  <h2>Something went wrong when attempting to save this card:</h2>
  <p><%= @message %></p>
<% end %>

<%= link_to "Show all of my saved payment methods", payment_methods_index_path %>
<%= link_to "Return Home", home_index_path, :"data-turbolinks"=>false %>

app/views/bookings/show.html.erb
<h2>Success!</h2>
<h2>You booked a flight for $<%= @amount %></h2>
<p><%= link_to "Save my payment method", save_payment_method_path, method: :post %> for future use.</p>
<%= link_to "Return Home", home_index_path, :"data-turbolinks"=>false %>

app/views/home/index.html.erb
<head>
  <script src="https://core.spreedly.com/iframe/express-2.min.js"></script>
</head>

<div class="flights-grid-container">
  <ul class="flights-grid">
    <li class="grid-title">Available Flights</li>
    <ul class="grid-headers">
      <li>Leaving From</li>
      <li>Going To</li>
      <li>Cost</li>
    </ul>
    <% @flights.each do |flight| %>
      <% receiver = rand(2) == 1 ? 'expedia' : 'none' %>
      <ul class="flight">
        <li><%= flight[:departure] %></li>
        <li><%= flight[:destination] %></li>
        <li><%= flight[:cost] %></li>
        <li class="button-container">
          <form action="/order" method="post" id="express-form">
            <input type="hidden" name="authenticity_token" value="form_authenticity_token">
            <input type="hidden" name="payment_method_token" id="payment_method_token">
            <input type="hidden" name="amount" value="<%= flight[:cost] %>">
            <input type="hidden" name="receiver" value="<%= receiver %>">
            <input type="button" class="btn highlight" value="Book Now!" onclick="callSpreedly(<%= flight[:cost] %>)">
          </form>
          <%= link_to "Add to Cart", cart_path(flight: flight), method: :post, class: "btn" %>
        </li>
        <% if receiver == 'expedia' %>
          <%= image_tag "expedia_logo.png", class: "expedia-logo" %>
        <% end %>
      </ul>
    <% end %>
  </ul>
  <div class="controls-container">
    <%= link_to "Proceed to Checkout", checkout_path, :"data-turbolinks"=>false, class: "btn" %>
    <%= link_to "Clear Cart", clear_cart_path, method: :post, class: "btn" %>
    <%= link_to "Show All Transactions", bookings_index_path, class: "btn" %>
    <%= link_to "Show Saved Payment Methods", payment_methods_index_path, class: "btn" %>

  </div>
</div>

<script type="text/javascript">

function callSpreedly(cost) {
  SpreedlyExpress.init('3C7NRMKIvw2hUvkgic6P5AP0UsH', {
    "amount": cost,
    "company_name": "Spreedly Airlines"
  });
  SpreedlyExpress.openView();
}

SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {
  var tokenField = document.getElementById("payment_method_token");

  tokenField.setAttribute("value", token);

  var masterForm = document.getElementById('express-form');
  masterForm.submit();
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpreedlyAirlines</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h1 class="page-title">Welcome to Spreedly Airlines!</h1>
    </div>
    <div class="home-container">
      <%= yield %>
    </div>
  </body>
</html>